<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Check The Halls')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                        ->prependStylesheet($this->basePath('css/font-awesome.min.css'))
                        ->prependStylesheet($this->basePath('css/select2.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/app/imageUpload.js'))
            ->prependFile($this->basePath('js/vendor/bootstrap.min.js'))
            ->prependFile($this->basePath('js/vendor/select2.min.js'))
            ->prependFile($this->basePath('js/app/bootstrap-waitingfor.js'))
            ->prependFile($this->basePath('js/vendor/jquery-2.2.4.min.js'))
            ->prependFile($this->basePath('js/vendor/vue.min.js'))
        ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar">
                        </span>
                    </button>
                    <a class="navbar-brand" href="/"><span class="glyphicon glyphicon-home" aria-hidden="true"></span></a>
                    <a class="navbar-brand" href="/map"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></a>
                    <a class="navbar-brand" href="/add"><span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span></a>
                </div>
            </div>
        </nav>
            <?= $this->content; ?>
    
    </body>


</html>

