<?php
/**
 * @link      http://github.com/zendframework/ZendSkeletonApplication for the canonical source repository
 * @copyright Copyright (c) 2005-2016 Zend Technologies USA Inc. (http://www.zend.com)
 * @license   http://framework.zend.com/license/new-bsd New BSD License
 */

namespace HallsApplication\Controller;

use HallsApplication\Service\HallsService;
use Zend\Mvc\Controller\AbstractActionController;
use Zend\View\Model\ViewModel;
use HallsApplication\Table\HallsTable;

class IndexController extends AbstractActionController
{
    private $hallsService;

    public function __construct(HallsService $hallsService)
    {
        $this->hallsService = $hallsService;
    }

    public function indexAction()
    {
        $hallsJson = $this->hallsService->getHallsAsJson();

        $viewData = [
            'hallsJson' => $hallsJson,
        ];
        
        $view = new ViewModel($viewData);
        $view->setTemplate('index');
        
        return $view;
    }

    public function __call($method, $params)
    {
        return parent::__call($method, $params); // TODO: Change the autogenerated stub
    }
}
