
<div id="app" class="container">
    <div class="addHallsForm">
        <div class="review-title">
            Add Review For {{ hall.name }}
        </div>

        </br>

        <form v-bind:class="{ 'has-error': form.nameinvalid }" class="form-horizontal">
            <div class="row">
                <div  class="col-sm-4 col-sm-offset-4 input-group">
                    <input v-model="submitter.name" type="text" class="textbox form-control has-error" placeholder="Your Name" aria-describedby="basic-addon1"/>
                    <span v-if="form.nameinvalid" class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>
                </div>
            </div>

            <br/>

            <div class="row ratings">
                <rating :name="'Location'" :rating.sync="review.rating.location"></rating>
            </div>
            <div class="row ratings">
                <rating :name="'Community'" :rating.sync="review.rating.community"></rating>
            </div>
            <div class="row ratings">
                <rating :name="'Comfort'" :rating.sync="review.rating.comfort"></rating>
            </div>
            <div class="row ratings">
                <rating :name="'Value For Money'" :rating.sync="review.rating.valueformoney"></rating>
            </div>
            <div class="row ratings">
                <rating :name="'Social Space'" :rating.sync="review.rating.socialspace"></rating>
            </div>
            
            <br/>
            
            <div class="col-sm-10 col-xs-offset-1 margin-bottom input-group">
                <textarea v-model="review.text" rows="10" class="form-control" aria-describedby="basic-addon1" placeholder="What do you think?"></textarea>
            </div>

            <div>
                <fileupload class="button-margin" :images.sync="uploadedimages" :name="'Add an Image'" :errortext="'File must be an Image'"></fileupload>
                <button @click.prevent="submit" type="button" class="button-margin col-sm-2 btn submit-button btn-lg">Submit</button>
            </div>

        </form>
    

    </div>
</div>

<template id="rating">
    <div class="col-xs-6 rating-text">{{ name }}</div>
    <div id="rating-location" @mousemove="mouseOver" @click="mouseClick" class="star-backer col-xs-4" :style="{'background': 'linear-gradient(to right,  #F14A46 ' + this.rating + '%, white ' + this.rating + '%)'}">
        <img class="star-image" src="/img/fivestars-v1.png"/>
    </div>
</template>



<?= $this->inlineScript()
    ->prependFile($this->basePath('js/app/addReviewPage.js'))
?>