<div id="app" class="container" xmlns="http://www.w3.org/1999/html">
<div class="hallProfile">

    <h1>{{ hall.hall_name }}</h1>

    <div class="row">
        <div id="myCarousel" class="col-xs-8 col-xs-offset-2 hallCarousel carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
                <li v-for="image in hall.images" v-bind:class="{ 'active': $index == 0}" data-target="#myCarousel" data-slide-to="{{ $index }}"></li>

            </ol>

            <!-- Wrapper for slides -->
            <div class="hallImage carousel-inner" role="listbox">

                <div v-for="image in hall.images" v-bind:class="{ 'active': $index == 0}" class="hallImage item">
                    <img src="/img/hallsImages/{{ image }}" class="hallImage">
                </div>

            </div>

            <!-- Left and right controls -->
            <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>

    <div class="row">
        <div class="hall-profile-address">
            {{ hall.address_first_line }}, {{ hall.address_second_line }}, {{ hall.address_city }}, {{ hall.address_postcode }}
        </div>
        <div class="hall-profile-uni">
            ({{ hall.university.name }})
        </div>
    </div>

    <br/>
    <br/>
    <br/>
    <div v-if="hall.reviews.length == 0">
        No Reviews
    </div>
    <div v-if="hall.reviews.length != 0">
        <div class="row ratings">
            <rating :name="'Location'" :rating="hall.ratings.totalLocation"></rating>
        </div>
        <div class="row ratings">
            <rating :name="'Community'" :rating="hall.ratings.totalCommunity"></rating>
        </div>
        <div class="row ratings">
            <rating :name="'Comfort'" :rating="hall.ratings.totalComfort"></rating>
        </div>
        <div class="row ratings">
            <rating :name="'Value For Money'" :rating="hall.ratings.totalValue"></rating>
        </div>
        <div class="row ratings">
            <rating :name="'Social Space'" :rating="hall.ratings.totalSocialSpace"></rating>
        </div>

        <br/>
        <br/>
        <br/>

        <div class="reviews">
            <span> Reviews: </span>
            <review v-for="review in hall.reviews" :review="review"></review>
        </div>
    </div>
    <button type="submit"
           class="btn btn-default"
            @click.prevent="addReview"
    >Add Your Own Review</button>
</div>
</div>


<template id="review">
    <div class="row">
    <div class="review col-xs-8 col-xs-offset-2">
        <div class="reviewer">{{ review.reviewer }} <span class="location-text"> From {{ review.location }}</span></div>
        <div class="review-text">
            <i class="fa fa-quote-left" aria-hidden="true"></i>

            <span>{{ review.review_text }}</span>

            <i class="fa fa-quote-right" aria-hidden="true"></i>
        </div>
    </div>
    </div>
    <br/>
</template>

<template id="rating">
    <div class="col-xs-6 rating-text">{{ name }}</div>
    <div id="rating-location" class="star-backer col-xs-4" :style="{'background': 'linear-gradient(to right,  #F14A46 ' + this.rating + '%, white ' + this.rating + '%)'}">
        <img class="star-image" src="/img/fivestars-v1.png"/>
    </div>
</template>

<?= $this->inlineScript()
    ->prependFile($this->basePath('js/app/hallProfilePage.js'))
?>