<?= $this->headLink()
    ->prependStylesheet($this->basePath('css/homePage.css'));
?>

<div class="row">
    <h2 class="title-box col-xs-4 col-xs-offset-4">
        Find the student accommodation that is perfect for you, using the reviews and experiences of past and current students who stayed in them.
    </h2>
</div>

<div class="row map-button-div">
    <button type="button" class="map-button col-sm-2 col-sm-offset-5 btn btn-lg">CHECK THE HALLS</button>
</div>